steps:
  # Step 1: Build the JAR file using Maven
  - name: 'maven:3.9.9'
    id: 'Build JAR'
    args: ['mvn','package']
    dir: 'container2'  # Path to the Java project

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/csci5409-454408/k8s-container2/container2:latest', '.']
    dir: 'container2'  # Path to the Dockerfile

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', 'us-central1-docker.pkg.dev/csci5409-454408/k8s-container2/container2:latest']

  # Step 4: Apply Deployment for Container 2
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Container 2'
    args: ['apply', '-f', '../k8s_files_container2/deployment2.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'

  # Step 5: Apply Service for Container 2
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Expose Container 2'
    args: ['apply', '-f', '../k8s_files_container2/service2.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
# Specify the Artifact Registry as the destination for the Docker image
images:
  - 'us-central1-docker.pkg.dev/csci5409-454408/k8s-container2/container2:latest'